name: CI

on: [push]

jobs:
  update:
    env:
      CONTROLS_FILENAME: controls_BRAVIA.txt 
    runs-on: ubuntu-latest
    steps: 
    - name: Extract branch name
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch
    - name: Checkout Repostory
      uses: actions/checkout@master
    - name: update controls files
      uses: fhem/fhem-controls-actions@master
      with:
        filename: controls_BRAVIA.txt 
    - name: update CHANGED
      run: |
        LOG=$(git log --pretty="%as - %s" --invert-grep --grep="Automatic updated controls and CHANGED" --grep="Merge" --grep="SVN upload")
        echo "$LOG"
        git log --pretty="%as - %s" --invert-grep --grep="Automatic updated controls and CHANGED" --grep="Merge" --grep="SVN upload" > CHANGED
    - name: git commit back
      run: |
        git config --global user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add  CHANGED controls_BRAVIA.txt || true
        git log -1 --name-only --pretty=format: | grep -Eo '[0-9]{2}_.*.pm$' && git commit CHANGED controls_BRAVIA.txt -m "Automatic updated controls and CHANGED" || true
    - name: git push
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ steps.extract_branch.outputs.branch }}
